build:
  phpunit:
    image: dangminhtruong/rails_base_with_ci
    commands:
    - cp config/database-ci.yml config/database.yml
    - bundle install
    - gem install bundle-audit
    - gem install rails_best_practices
    - gen install rspec
    - gem install scss_lint
    - RAILS_ENV=test rake db:create db:migrate
    - framgia-ci run
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ci_test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
