default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: test
  username: root
  password: root

development: &development
  <<: *default
  host: mysql
  database: ci_test

development_reader:
  <<: *development
  host: mysql

test: &test
  <<: *default
  host: mysql
  database: ci_test

test_reader:
  <<: *test
  host: mysql

production: &production
  <<: *default
  host: mysql
  database: ci_test

production_reader:
  <<: *production
  host: mysql
